### ISSUE TITLE
Question about the implementation of SGRU

### ISSUE THREAD

**Issue by nnniuzy** [zwd2016/GRU-SSU-AMG#1]
The equations I saw when I read the paper is shown in Figure 1, but the code implementation in lines 1441-1443 of the recurrent.py file is different.

> if self.implemetation == 2:
>     comparison = tf.less_equal(self.select_ratio * (z * h_tm1 + (1 - z) * hh), h_tm1)
>     h = tf.where(comparison, z * h_tm1 + (1 - z) * hh, h_tm1)

The above code represents that h_t = \tilde{h}_t if \tilde{h}_t <= h_{t-1}.

Or I may have misunderstood it, looking forward to your reply.

![equations](https://user-images.githubusercontent.com/33317516/168727136-24f00db4-51ae-48f7-8e37-8da6423b0129.jpg)

**Comment by nnniuzy** [comment]
![equations](https://user-images.githubusercontent.com/33317516/168726971-c69a53f3-3071-473a-8712-a9ecb1b8355f.jpg)

**Comment by zwd2016** [comment]
> The equations I saw when I read the paper is shown in Figure 1, but the code implementation in lines 1441-1443 of the recurrent.py file is different.
> 
> > if self.implemetation == 2:
> > comparison = tf.less_equal(self.select_ratio * (z * h_tm1 + (1 - z) * hh), h_tm1)
> > h = tf.where(comparison, z * h_tm1 + (1 - z) * hh, h_tm1)
> 
> The above code represents that h_t = \tilde{h}_t if \tilde{h}_t <= h_{t-1}.
> 
> Or I may have misunderstood it, looking forward to your reply.
> 
> ![equations](https://user-images.githubusercontent.com/33317516/168727136-24f00db4-51ae-48f7-8e37-8da6423b0129.jpg)

Hi, 
Thank you for reading the article and code carefully. I think I uploaded another version of the SGRU implementation. The core purpose of our SGRU is to judge the numerical fluctuation of the hidden weights from $t-1$ to $t$, which means that as long as there is a clear difference between $h^{(T-1)}$ and $h_{(t)}$. Thus, I suggest you change the inequality direction in this code. In fact, the direction of inequality is also an empirical exploration.
Best regards!
May. 17th, 2022

**Comment by nnniuzy** [comment]
> 

Thanks for your response.
